spring:
  application:
    name: auth-center

server:
  port: 8762

eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/

logging:
  level:
    org.springframework.security: DEBUG
