spring:
  application:
    name: message-center
  datasource:
    url: jdbc:mysql://192.168.1.123:3306/ocpp?serverTimezone=GMT%2B8
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true

server:
  port: 9999

eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/