spring:
  application:
    name: zuul-gateway
  main:
    allow-bean-definition-overriding: true

server:
  port: 9200

eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/

zuul:
  ignored-services: "*"
  add-host-header: false
  routes:
    message-publisher:
      path: /message/**
    basic-info:
      path: /basic/**

