spring:
  application:
    name: zuul-gateway
  main:
    allow-bean-definition-overriding: true

server:
  port: 9200

eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/

security:
  oauth2:
    client:
      client-id: open-api
      client-secret: open-secret
      user-authorization-uri: http://127.0.0.1:9100/uaa/oauth/authorize
      access-token-uri: http://127.0.0.1:9100/uaa/oauth/token
      registered-redirect-uri: http://127.0.0.1:9200/login
    resource:
      jwt:
        key-uri: http://127.0.0.1:9100/uaa/oauth/token_key
        key-value: 123
    sso:
      login-path: /login

zuul:
  ignored-services: "*"
  add-host-header: false
  routes:
    message-publisher:
      path: /message/**
    basic-info:
      path: /basic/**
  include-debug-header: true

ribbon:
  ReadTimeout: 10000

logging:
  level:
    com.netflix.zuul: DEBUG
    org.springframework.cloud.netflix.zuul: DEBUG