server:
  port: 8080
  servlet:
    context-path: /client

spring:
  application:
    name: ewip-client
  thymeleaf:
    cache: false

eureka:
  client:
    service-url:
      default-zone: http://192.168.2.102:8761/eureka/
  instance:
    ip-address: true