spring:
  application:
    name: message-publisher
  datasource:
    url: jdbc:mysql://192.168.1.123:3306/zhxu?serverTimezone=GMT%2B8
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL57Dialect
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true

server:
  port: 9999

eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/