spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
logging:
  file: D:/ewip/log/ewip-server/ewip-server.log
  level: [
    com.hyt.server.mapper.config: debug,
    com.hyt.server.mapper.sys: debug
  ]

server:
  connection-timeout: 5s
