spring:
  application:
    name: message-publisher
  datasource:
    url: jdbc:mysql://192.168.1.123:3306/ewip-huachi
    username: root
    password: root

server:
  port: 9999

eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/